### ISSUE TITLE
weave-scope forwarding doesn't work

### ISSUE THREAD

**Issue by joscha-alisch** [pixel-point/kube-forwarder#17]
Currently, it seems like it is not possible to use port forwarding with weave-scope (https://github.com/weaveworks/scope)

On the command-line it works fine with:
```bash
~ kubectl port-forward svc/weave-scope-weave-scope -n weave-scope 4040:80
Forwarding from 127.0.0.1:4040 -> 4040
Forwarding from [::1]:4040 -> 4040
Handling connection for 4040
```
I immediately see the weave-scope UI in the browser.
Interestingly it directly forwards to port `4040` instead of `80`. 

When using the same config in kube-forwarder I don't get a response when trying to access the UI. Just the browsers "Waiting for localhost..."

![image](https://user-images.githubusercontent.com/9500791/61771807-0854a780-adf1-11e9-8e73-1d50f5535d93.png)

In the console I don't see any errors and I'm not sure if there is an option to enable debug mode.

OS: 
```
Linux 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64 GNU/Linux
```

gcloud sdk:
```
Google Cloud SDK 254.0.0
alpha 2019.07.15
beta 2019.07.15
bq 2.0.45
core 2019.07.15
gsutil 4.40
kubectl 2019.07.15
```

**Comment by proAlexandr** [comment]
Hi @joscha-alisch 
Thanks a lot for the bug report. I discovered that implementation port forwarding for "service" kind does have few issues. I am going to fix them in the next release.

Issues:
* Kube Forwarder allows forwarding to ports which service does not have. I think it has to throw an error as kubectl does 
```
$  kubectl port-forward svc/postgres -n malware-index-dev 4040:80
> error: Service postgres does not have a service port 80 
```
* Kube Forwarder doesn't have something which looks like mort mapping. So it doesn't directly forwards to port 4040 instead of 80 as it is shown in the issue description.

**Comment by proAlexandr** [comment]
@joscha-alisch HI, we've just released a [new version](https://github.com/pixel-point/kube-forwarder/releases/tag/v1.3.2). Port mapping is implemented there. Could you please check it?

**Comment by joscha-alisch** [comment]
Hi @proAlexandr , it does indeed work now. Thank you!
