### ISSUE TITLE
Behavior differs from kubectl port-forward service

### ISSUE THREAD

**Issue by Adiqq** [pixel-point/kube-forwarder#23]
I can port forward connection to service with kubectl:
`kubectl port-forward -n some-namespace svc/postgres-somecluster-postgresql 5432:5432`
However this same does not work correctly with kube-forwarder, because I can't connect with pgAdmin to database. Kube-forwarder indicates that port forward is running correctly.

I'm not sure if that's specific to cluster or postgresql, but I'm using this helm chart to deploy postgres: https://github.com/helm/charts/tree/master/stable/postgresql
Problems occurs on kube-forwarder, version 1.4.0.

Maybe application could show some logs, like kubectl port-forward does, to help troubleshoot this kind of issues?

**Comment by proAlexandr** [comment]
Hi @Adiqq, thanks for using Kube Forwarder and the bug report.
I have reproduced the issue. I hope we will be able to fix it soon.

**Comment by proAlexandr** [comment]
Hi, @Adiqq!
The issue was because of Kube Forwarder didn't support named ports which services can have.
We have released a [new version](https://github.com/pixel-point/kube-forwarder/releases/tag/v1.4.2). The version should work well with named ports. I hope it will help you.
Thank you that you have found a bug and helped us make the app better!
