### ISSUE TITLE
DEAD REPO ? NEED HELP / NEW MAINTAINERS ?

### ISSUE THREAD

**Issue by fredleger** [pixel-point/kube-forwarder#95]
Seems that this excelent tool with not so much alternatives but very famous is not working any more on many edge cases because it it outdated (dependencies / LE CA etc ...)

The beauty of open source is that we can help and make this work. Do you need any help with the project ? PRs (7 unmerged so far) ? Maintenainers ? 

Sorry if that sound rough but i do want to see this tool updated and worked again. Even Mirantis Lens with it's included port-forwarding is not so easy to use.

**Comment by urbanswelt** [comment]
It`s a shame ... such a beauty no maintenance =/

I test with the latest active LTS Version and a hard reset at this time , fingers cross !
But looks nearly like a fresh start would be better ;D

`
+ npm install --legacy-peer-deps
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated eslint-plugin-standard@5.0.0: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
npm WARN deprecated eslint-loader@4.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 1772 packages, and audited 1773 packages in 3m

184 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (3 low, 5 moderate, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

`

**Comment by chaoyangnz** [comment]
I'd like to help maintain

**Comment by hcavarsan** [comment]
JFTY, we are discussing this in another thread and I opened a PR updating overall dependencies here, now kube-forwarder it’s working with node 22 and pnpm (in my fork) 


PR:
https://github.com/pixel-point/kube-forwarder/pull/108

Issue:
https://github.com/pixel-point/kube-forwarder/issues/100

**Comment by fredleger** [comment]
@hcavarsan thank you putting effort in maintaining this great project ! Would be pleased to test your fork if needed !

We can close this issue then

**Comment by fredleger** [comment]
closed in favor of #100
